'use strict'

var validator = require('validator');
var nodemailer = require('nodemailer');

var fs = require('fs');
var path = require('path');
var Email = require('../models/email');
var jwt = require('../services/jwt');

var controller = {
  

  	send: function(req, res)
    {
      
      // Recoger los parametros de la petición

  	//	var params = req.body;

  	//	Validar los datos
  		try{
  			var validate_name    = !validator.isEmpty(req.body.name);
  			var validate_email   = !validator.isEmpty(req.body.email);
  			var validate_message = !validator.isEmpty(req.body.message);
  			//console.log(validate_name, validate_surname, validate_email, validate_password);
  		}catch(err){
        return console.log("faltan datos para enviar el correo");
  		}
      
      if(validate_name && validate_email && validate_message )
      {
        var mailOpts;

          //Setup Nodemailer transport, I chose gmail. Create an application-specific password to avoid problems.
          var transport = nodemailer.createTransport({
            host: "smtp.mailtrap.io",
            port: 2525,
            auth: {
              user: "c6d4b8e2f225c5", //generated by Mailtrap
              pass: "096f01eaf6fc0a" //generated by Mailtrap
            }
          });
          
    
          var mailoutput = "<html>\n\
                          <body>\n\
                          <table>\n\
                          <tr>\n\
                          <td>Name:" + req.body.name + "</td>\n\
                          </tr>\n\
                          <tr>\n\
                          <td>Email:" + req.body.email + "</td>\n\
                          </tr>\n\
                          <tr>\n\
                          <td>Message:" + req.body.message + "</td>\n\
                          </tr>\n\
                          </table></body></html>";
          //Mail options
          // var mailOptions = {
          //     from: 'student',
          //     to: 'kevinmcgregor66@protonmail.com',
          //     subject: 'Nice Nodemailer test',
          //     text: 'Hey there, it’s our first message sent with Nodemailer ;) ', 
          //     html: '<b>Hey there! </b><br> probando el mensaje'
          // };
          mailOpts = {
              to: "kevinmcgregor66@protonmail.com",
              subject: "mensaje recibido por la web",
              html: mailoutput
          };
          // transport.sendMail(mailOptions, (error, info) => {
          //     if (error) {
          //         return console.log(error);
          //     }
          //     console.log('Message enviado: %s', info.messageId);
          // });

          transport.sendMail(mailOpts, function (error, res) {
              if (error) {
                  // res.send("Email could not send due to error" +error);
                  return console.log(error);
              }
          });
          console.log('Message sent successfully!');
              //res.render('email.js');
      
      //console.log(query.sql);

  //});
    }
  },  
  
  
  







}  





module.exports = controller;